echo;
echo;
echo;
echo "Daisy, Daisy, give me your answer do,";
echo "I'm half crazy all for the love of you,";
echo "It won't be a stylish marriage,"; 
echo "I can't afford a carriage,";
echo "But you'll look sweet...";
echo "Upon the seat...";
echo "of a...";
echo "bicycle...";
echo "built...";
echo "for...";
echo "two...";
echo "...";
echo;
echo;
echo;
